version: "3.3"
services:

  code:
    container_name: code
    depends_on:
      - db-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/results
    networks:
      - backend

  db-container:
    image: linuxserver/mariadb:latest
    container_name: db-container
    restart: always
    volumes:
      - ./db:/config
    networks:
      - backend
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

networks:
    backend:
