version: "3.3"
services:
  db:
    image: mariadb:10.5.8
    container_name: db-container
    restart: always
    volumes:
        - db-data:/var/lib/mariadb
        - base:/docker-entrypoint-initdb.d/
    networks:
        - backend
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
        MYSQL_DATABASE: bbdb
        MYSQL_ROOT_PASSWORD: pass
        PORT: 3306
    ports:
        - 5000:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
volumes:
    db-data:
    base:
    
networks:
    frontend:
    backend:
